"use strict";
sap.ui.define([], function () {
	"use strict";
	var month = (new Date().getMonth() + 1).toString();
	var year = (new Date().getFullYear()).toString();

	if (month.length < 2) {
		month = '0' + month;
	}
	var date = '01' + '/' + month + '/' + year; 
	var date2 = '01' + '/' + month + '/' + year; 

	return {
		Simulation: true,
		StateList: { 	highlight: "Success",
						info: "Processado"},
	   SelectedTipo: 0,					
	   TipoCollection :[{"Id": 0, Name: ""},
{"Id": 1, Name: "A1"},
{"Id": 2, Name: "A2"},
{"Id": 3, Name: "A4"},
{"Id": 4, Name: "A5"},
{"Id": 5, Name: "B1"},
{"Id": 6, Name: "B2"},
{"Id": 7, Name: "B3"},
{"Id": 8, Name: "B4"},
{"Id": 9, Name: "B5"},
{"Id": 10, Name: "B6"},
{"Id": 11, Name: "B7"},
{"Id": 12, Name: "C1"},
{"Id": 13, Name: "C5"},
{"Id": 14, Name: "CR"},
{"Id": 15, Name: "E1"},
{"Id": 16, Name: "E2"},
{"Id": 17, Name: "E4"},
{"Id": 18, Name: "E5"},
{"Id": 19, Name: "E6"},
{"Id": 20, Name: "EM"},
{"Id": 21, Name: "EN"},
{"Id": 22, Name: "G1"},
{"Id": 23, Name: "G4"},
{"Id": 24, Name: "N1"},
{"Id": 25, Name: "N2"},
{"Id": 26, Name: "N3"},
{"Id": 27, Name: "N4"},
{"Id": 28, Name: "N5"},
{"Id": 29, Name: "O1"},
{"Id": 30, Name: "O2"},
{"Id": 31, Name: "O3"},
{"Id": 32, Name: "O4"},
{"Id": 33, Name: "O5"},
{"Id": 34, Name: "R1"},
{"Id": 35, Name: "R4"},
{"Id": 36, Name: "RE"},
{"Id": 37, Name: "S1"},
{"Id": 38, Name: "S2"},
{"Id": 39, Name: "T1"},
{"Id": 40, Name: "T2"},
{"Id": 41, Name: "U1"},
{"Id": 42, Name: "U2"},
{"Id": 43, Name: "X1"},
{"Id": 44, Name: "X2"},
{"Id": 45, Name: "X3"},
{"Id": 46, Name: "X4"},
{"Id": 47, Name: "X5"},
{"Id": 48, Name: "Y1"},
{"Id": 49, Name: "Y2"},
{"Id": 50, Name: "Y3"},
{"Id": 51, Name: "Y4"},
{"Id": 52, Name: "Y5"},
{"Id": 53, Name: "Z1"},
{"Id": 54, Name: "Z2"},
{"Id": 55, Name: "Z3"},
{"Id": 56, Name: "Z4"},
{"Id": 57, Name: "Z5"},
{"Id": 58, Name: "Z6"},
{"Id": 59, Name: "Z7"},
{"Id": 60, Name: "Z8"},
{"Id": 61, Name: "ZA"},
{"Id": 62, Name: "ZB"},
{"Id": 63, Name: "ZC"},
{"Id": 64, Name: "ZI"},
{"Id": 65, Name: "ZN"},
{"Id": 66, Name: "ZR"},
{"Id": 67, Name: "ZS"},
{"Id": 68, Name: "ZW"}
				],
					
		Results: [],
		Companies: [],
		Branchs: [],
		SelectedCompany: 0,
		SelectedBranch: 0,
		SelectedBranch2: 0,
		SelectedPeriod: date,
	    SelectedPeriod2: date2,
		CompanyCollection: [],
		BranchCollection: [],
        NfidValue: ""
	};
});